### ISSUE TITLE
Reproduce the issue 4440 from jekyll

### ISSUE THREAD

**Issue by CGarces** [CGarces/jekyll-seo-tag-test#1]
Trying to reproduce the [issue with the slash](https://github.com/jekyll/jekyll/issues/4440)

[This should work] (https://github.com/CGarces/jekyll-seo-tag-test/blob/gh-pages/_posts/2016-01-29-I-finally-have-a-site-2.md)

[But this one not] (https://github.com/CGarces/jekyll-seo-tag-test/blob/gh-pages/_posts/2016-01-29-I-finally-have-a-site.md) is the same that the used by @daattali 

But at this time booth works.

**Comment by daattali** [comment]
I'm not sure if you understand the problem. Yesterday, my blog post that had permalink ":title" has a URL of "/foobar/", and all the links online pointed to that URL. Today, a page with permalink ":title" will result in URL of "/foobar", and if you try to go to "/foobar/" you will get a 404 error.

You haven't disproved what I'm saying - in your site , the pages do **not** have a trailing slash.

I've already confirmed with Jekyll that this is indeed a change of behaviour in Jekyll 3, and there is a known solution to it, so if you aren't affected by it, don't worry about it!

**Comment by CGarces** [comment]
Not I'm sure that I NOT understand the problem.
But i like to test the error. I have 1 sites hat use the `permalink: "/:title"` (without slash)

But i think that I got it.
[In this page] (https://github.com/CGarces/jekyll-seo-tag-test/blob/gh-pages/_posts/2016-01-29-I-finally-have-a-site.md)

The `permalink` is `permalink: /2016/01/29/I-finally-have-a-site`
`http://cgarces.github.io/jekyll-seo-tag-test/2016/01/29/I-finally-have-a-site` works.
But `http://cgarces.github.io/jekyll-seo-tag-test/2016/01/29/I-finally-have-a-site/` get a 404.

But looks like this only happens if you specify a permalink manually, probably Jekyll render one file instead of one folder + index.hml for that post.

in any case that means that my sites not are affected.

**Comment by daattali** [comment]
Yes, exactly. 2 days ago, `http://cgarces.github.io/jekyll-seo-tag-test/2016/01/29/I-finally-have-a-site/` would have worked and it would have been the default URL by Jekyll.

**Comment by CGarces** [comment]
Sample code...
```
---
layout: default
permalink: /2016/01/29/I-finally-have-a-site
---

Some text
```

Rendered by Jekyll

_site/2016/01/29/I-finally-have-a-site.html

So if you not put a slash add `.html' instead add an slash and create a file instead of a folder + index.html.

Thanks to help me understand the issue.
